# version: '3'
# services:
#   app:
#     build:
#       context: /.
#       dockerfile: DockerFile
#     image: truegas
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       - NODE_ENV=development
#       - MONGODB_URI=mongodb://db:27017/truegas
#     volumes:
#       - .:/app
#   db:
#     image: mongo
#     volumes:
#       - dbdata:/data/db

# volumes:
#   dbdata:
#     driver: local

version: '3'
services:
  app:
    image: truegas
    build: 
      context: ./
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    restart: always  
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/truegas
    volumes:
      - ./:/app
  db:
    image: mongo
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
    driver: local